resource-pack:
  enabled: false
  force: false
  url: ""
  sha1: ""

notes:
  right-click-deposit: true

messages:
  prefix: "&6&lSmartWithdraw &8» "

  withdraw-success: "&aSuccessfully withdrew &f₹%amount%"
  insufficient-funds: "&cYou do not have enough money."
  invalid-amount: "&cPlease enter a valid amount."
  deposit-success: "&aDeposited &f₹%amount%"
