name: SmartWithdraw
version: 1.0.0
main: com.smartwithdraw.SmartWithdraw
api-version: '1.21'

depend:

- Vault

commands:
  withdraw:
    description: Withdraw money into notes
usage: /withdraw <amount>

smartwithdraw:
description: SmartWithdraw Help
usage: /smartwithdraw
aliases:
- sw

permissions:
smartwithdraw.withdraw:
default: true
